//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map(Locale.init)
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.file` struct is generated, and contains static references to 83 files.
  struct file {
    /// Resource file `005tnxzUly8gab4i2r73xj30u00u0js8.jpg`.
    static let tnxzUly8gab4i2r73xj30u00u0js8Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "005tnxzUly8gab4i2r73xj30u00u0js8", pathExtension: "jpg")
    /// Resource file `006PdkDogy1gap6ngiyn3j30u011idle.jpg`.
    static let pdkDogy1gap6ngiyn3j30u011idleJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "006PdkDogy1gap6ngiyn3j30u011idle", pathExtension: "jpg")
    /// Resource file `006PdkDogy1gap6ngj12ej30u011itf7.jpg`.
    static let pdkDogy1gap6ngj12ej30u011itf7Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "006PdkDogy1gap6ngj12ej30u011itf7", pathExtension: "jpg")
    /// Resource file `006PdkDoly8ffywe2fq39j304g04gwed.jpg`.
    static let pdkDoly8ffywe2fq39j304g04gwedJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "006PdkDoly8ffywe2fq39j304g04gwed", pathExtension: "jpg")
    /// Resource file `006gWxMEly1gavap86qr9j30ht0qo40t.jpg`.
    static let gWxMEly1gavap86qr9j30ht0qo40tJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "006gWxMEly1gavap86qr9j30ht0qo40t", pathExtension: "jpg")
    /// Resource file `006gWxMEly1gavap88gttj30hs0a0dgf.jpg`.
    static let gWxMEly1gavap88gttj30hs0a0dgfJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "006gWxMEly1gavap88gttj30hs0a0dgf", pathExtension: "jpg")
    /// Resource file `006gWxMEly1gavap8dywoj30hs0bwq48.jpg`.
    static let gWxMEly1gavap8dywoj30hs0bwq48Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "006gWxMEly1gavap8dywoj30hs0bwq48", pathExtension: "jpg")
    /// Resource file `006gWxMEly1gavap8vsqaj30hs0bwgm6.jpg`.
    static let gWxMEly1gavap8vsqaj30hs0bwgm6Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "006gWxMEly1gavap8vsqaj30hs0bwgm6", pathExtension: "jpg")
    /// Resource file `006gWxMEly8g0bjpl3ynij30kv0kv773.jpg`.
    static let gWxMEly8g0bjpl3ynij30kv0kv773Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "006gWxMEly8g0bjpl3ynij30kv0kv773", pathExtension: "jpg")
    /// Resource file `4e7f0c83gy1gam2misv31j21hc0u016k.jpg`.
    static let e7f0c83gy1gam2misv31j21hc0u016kJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "4e7f0c83gy1gam2misv31j21hc0u016k", pathExtension: "jpg")
    /// Resource file `4e7f0c83gy1gam2mjhk8zj21hc0v6wnx.jpg`.
    static let e7f0c83gy1gam2mjhk8zj21hc0v6wnxJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "4e7f0c83gy1gam2mjhk8zj21hc0v6wnx", pathExtension: "jpg")
    /// Resource file `4e7f0c83gy1gam2ml6nucj22tc240kjl.jpg`.
    static let e7f0c83gy1gam2ml6nucj22tc240kjlJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "4e7f0c83gy1gam2ml6nucj22tc240kjl", pathExtension: "jpg")
    /// Resource file `4e7f0c83gy1gam2mn58d3j22tc240qv5.jpg`.
    static let e7f0c83gy1gam2mn58d3j22tc240qv5Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "4e7f0c83gy1gam2mn58d3j22tc240qv5", pathExtension: "jpg")
    /// Resource file `4e7f0c83gy1gam2mp0x4pj22tc240u0x.jpg`.
    static let e7f0c83gy1gam2mp0x4pj22tc240u0xJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "4e7f0c83gy1gam2mp0x4pj22tc240u0x", pathExtension: "jpg")
    /// Resource file `4e7f0c83gy1gam2mr1b81j22tc2407wi.jpg`.
    static let e7f0c83gy1gam2mr1b81j22tc2407wiJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "4e7f0c83gy1gam2mr1b81j22tc2407wi", pathExtension: "jpg")
    /// Resource file `4e7f0c83ly8g1ho507078j20ro0rojtq.jpg`.
    static let e7f0c83ly8g1ho507078j20ro0rojtqJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "4e7f0c83ly8g1ho507078j20ro0rojtq", pathExtension: "jpg")
    /// Resource file `630584a6gy1gau54zgaxhj20m80et0vq.jpg`.
    static let a6gy1gau54zgaxhj20m80et0vqJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "630584a6gy1gau54zgaxhj20m80et0vq", pathExtension: "jpg")
    /// Resource file `630584a6gy1gau54zl806j20m80etmzo.jpg`.
    static let a6gy1gau54zl806j20m80etmzoJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "630584a6gy1gau54zl806j20m80etmzo", pathExtension: "jpg")
    /// Resource file `630584a6gy1gau54zm4dtj20m80dftbv.jpg`.
    static let a6gy1gau54zm4dtj20m80dftbvJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "630584a6gy1gau54zm4dtj20m80dftbv", pathExtension: "jpg")
    /// Resource file `630584a6gy1gau54zyj61j20m80etn07.jpg`.
    static let a6gy1gau54zyj61j20m80etn07Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "630584a6gy1gau54zyj61j20m80etn07", pathExtension: "jpg")
    /// Resource file `630584a6ly8fqs5wwkkmrj20ku0kuta7.jpg`.
    static let a6ly8fqs5wwkkmrj20ku0kuta7Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "630584a6ly8fqs5wwkkmrj20ku0kuta7", pathExtension: "jpg")
    /// Resource file `648ed25bjw8est9nqrtnij20500503yr.jpg`.
    static let ed25bjw8est9nqrtnij20500503yrJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "648ed25bjw8est9nqrtnij20500503yr", pathExtension: "jpg")
    /// Resource file `6a2afec3gy1gaulykcejqj20t5145wns.jpg`.
    static let a2afec3gy1gaulykcejqj20t5145wnsJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "6a2afec3gy1gaulykcejqj20t5145wns", pathExtension: "jpg")
    /// Resource file `6a2afec3jw8fb4ld0qf2gj20e80dsdfz.jpg`.
    static let a2afec3jw8fb4ld0qf2gj20e80dsdfzJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "6a2afec3jw8fb4ld0qf2gj20e80dsdfz", pathExtension: "jpg")
    /// Resource file `6ec3b446gy1gavd4xud8lj20j60qkwj0.jpg`.
    static let ec3b446gy1gavd4xud8lj20j60qkwj0Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "6ec3b446gy1gavd4xud8lj20j60qkwj0", pathExtension: "jpg")
    /// Resource file `6ec3b446gy1gavd51jc4lj20j60pmwhl.jpg`.
    static let ec3b446gy1gavd51jc4lj20j60pmwhlJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "6ec3b446gy1gavd51jc4lj20j60pmwhl", pathExtension: "jpg")
    /// Resource file `6ec3b446gy1gavd523embj20j60pytd6.jpg`.
    static let ec3b446gy1gavd523embj20j60pytd6Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "6ec3b446gy1gavd523embj20j60pytd6", pathExtension: "jpg")
    /// Resource file `6ec3b446jw1e8qgp5bmzyj2050050aa8.jpg`.
    static let ec3b446jw1e8qgp5bmzyj2050050aa8Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "6ec3b446jw1e8qgp5bmzyj2050050aa8", pathExtension: "jpg")
    /// Resource file `700a34f6gy1gaunswwui7j20j60pl78e.jpg`.
    static let a34f6gy1gaunswwui7j20j60pl78eJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "700a34f6gy1gaunswwui7j20j60pl78e", pathExtension: "jpg")
    /// Resource file `700a34f6gy1gaunswxtlrj20j60pkgok.jpg`.
    static let a34f6gy1gaunswxtlrj20j60pkgokJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "700a34f6gy1gaunswxtlrj20j60pkgok", pathExtension: "jpg")
    /// Resource file `700a34f6gy1gaunswy5qnj20j60pkadk.jpg`.
    static let a34f6gy1gaunswy5qnj20j60pkadkJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "700a34f6gy1gaunswy5qnj20j60pkadk", pathExtension: "jpg")
    /// Resource file `700a34f6gy1gaunsx2jywj20j60pkaeu.jpg`.
    static let a34f6gy1gaunsx2jywj20j60pkaeuJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "700a34f6gy1gaunsx2jywj20j60pkaeu", pathExtension: "jpg")
    /// Resource file `700a34f6gy1gaunsxgzixj20j60edmz8.jpg`.
    static let a34f6gy1gaunsxgzixj20j60edmz8Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "700a34f6gy1gaunsxgzixj20j60edmz8", pathExtension: "jpg")
    /// Resource file `700a34f6gy1gaunsxhp4pj20j60pkn1k.jpg`.
    static let a34f6gy1gaunsxhp4pj20j60pkn1kJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "700a34f6gy1gaunsxhp4pj20j60pkn1k", pathExtension: "jpg")
    /// Resource file `700a34f6ly8g9a29rjt92j20fn0iqdg8.jpg`.
    static let a34f6ly8g9a29rjt92j20fn0iqdg8Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "700a34f6ly8g9a29rjt92j20fn0iqdg8", pathExtension: "jpg")
    /// Resource file `76297935ly1gatz89dzblj23402c0qv6.jpg`.
    static let ly1gatz89dzblj23402c0qv6Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "76297935ly1gatz89dzblj23402c0qv6", pathExtension: "jpg")
    /// Resource file `76297935ly1gatz8g5rvxj22c03401kz.jpg`.
    static let ly1gatz8g5rvxj22c03401kzJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "76297935ly1gatz8g5rvxj22c03401kz", pathExtension: "jpg")
    /// Resource file `76297935ly1gatz8k5itij22c02c01ky.jpg`.
    static let ly1gatz8k5itij22c02c01kyJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "76297935ly1gatz8k5itij22c02c01ky", pathExtension: "jpg")
    /// Resource file `76297935ly1gatz8obqvkj22c0340npe.jpg`.
    static let ly1gatz8obqvkj22c0340npeJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "76297935ly1gatz8obqvkj22c0340npe", pathExtension: "jpg")
    /// Resource file `76297935ly8g4phfkq68hj20u00u0mzt.jpg`.
    static let ly8g4phfkq68hj20u00u0mztJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "76297935ly8g4phfkq68hj20u00u0mzt", pathExtension: "jpg")
    /// Resource file `7f9147a5ly1fzxlgxgzpij20e90fltsj.jpg`.
    static let f9147a5ly1fzxlgxgzpij20e90fltsjJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "7f9147a5ly1fzxlgxgzpij20e90fltsj", pathExtension: "jpg")
    /// Resource file `7f9147a5ly1fzxlh4ovuej20e90fl4fo.jpg`.
    static let f9147a5ly1fzxlh4ovuej20e90fl4foJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "7f9147a5ly1fzxlh4ovuej20e90fl4fo", pathExtension: "jpg")
    /// Resource file `7f9147a5ly1fzxlh6hzdnj20e90fl7me.jpg`.
    static let f9147a5ly1fzxlh6hzdnj20e90fl7meJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "7f9147a5ly1fzxlh6hzdnj20e90fl7me", pathExtension: "jpg")
    /// Resource file `8697cf1ely8gashxj3b09j20u00u040v.jpg`.
    static let cf1ely8gashxj3b09j20u00u040vJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "8697cf1ely8gashxj3b09j20u00u040v", pathExtension: "jpg")
    /// Resource file `8a0b5544gy1gauy2ex786j20u0129aed.jpg`.
    static let a0b5544gy1gauy2ex786j20u0129aedJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "8a0b5544gy1gauy2ex786j20u0129aed", pathExtension: "jpg")
    /// Resource file `8a0b5544gy1gauy2flua6j20u00hitab.jpg`.
    static let a0b5544gy1gauy2flua6j20u00hitabJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "8a0b5544gy1gauy2flua6j20u00hitab", pathExtension: "jpg")
    /// Resource file `8a0b5544gy1gauy2g35yoj20u00fomzf.jpg`.
    static let a0b5544gy1gauy2g35yoj20u00fomzfJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "8a0b5544gy1gauy2g35yoj20u00fomzf", pathExtension: "jpg")
    /// Resource file `8a0b5544gy1gauy2gmkg9j20u00gegnp.jpg`.
    static let a0b5544gy1gauy2gmkg9j20u00gegnpJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "8a0b5544gy1gauy2gmkg9j20u00gegnp", pathExtension: "jpg")
    /// Resource file `8a0b5544gy1gauy2gz000j20u00n6wgj.jpg`.
    static let a0b5544gy1gauy2gz000j20u00n6wgjJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "8a0b5544gy1gauy2gz000j20u00n6wgj", pathExtension: "jpg")
    /// Resource file `8a0b5544gy1gauy2hcozsj20u01czdiy.jpg`.
    static let a0b5544gy1gauy2hcozsj20u01czdiyJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "8a0b5544gy1gauy2hcozsj20u01czdiy", pathExtension: "jpg")
    /// Resource file `8a0b5544jw1e8qgp5bmzyj2050050aa8.jpg`.
    static let a0b5544jw1e8qgp5bmzyj2050050aa8Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "8a0b5544jw1e8qgp5bmzyj2050050aa8", pathExtension: "jpg")
    /// Resource file `9dc7402fgy1gavd367p0pj20j60nywic.jpg`.
    static let dc7402fgy1gavd367p0pj20j60nywicJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "9dc7402fgy1gavd367p0pj20j60nywic", pathExtension: "jpg")
    /// Resource file `9dc7402fgy1gavd37l9nwj20j60ny44q.jpg`.
    static let dc7402fgy1gavd37l9nwj20j60ny44qJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "9dc7402fgy1gavd37l9nwj20j60ny44q", pathExtension: "jpg")
    /// Resource file `9dc7402fgy1gavd38kqjtj20j60nyn1d.jpg`.
    static let dc7402fgy1gavd38kqjtj20j60nyn1dJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "9dc7402fgy1gavd38kqjtj20j60nyn1d", pathExtension: "jpg")
    /// Resource file `9dc7402fgy1gavd38wwlrj20j60nyq6y.jpg`.
    static let dc7402fgy1gavd38wwlrj20j60nyq6yJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "9dc7402fgy1gavd38wwlrj20j60nyq6y", pathExtension: "jpg")
    /// Resource file `9dc7402fgy1gavd39ba15j20j60nywii.jpg`.
    static let dc7402fgy1gavd39ba15j20j60nywiiJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "9dc7402fgy1gavd39ba15j20j60nywii", pathExtension: "jpg")
    /// Resource file `9dc7402fjw1e8qgp5bmzyj2050050aa8.jpg`.
    static let dc7402fjw1e8qgp5bmzyj2050050aa8Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "9dc7402fjw1e8qgp5bmzyj2050050aa8", pathExtension: "jpg")
    /// Resource file `PostListData_hot_1.json`.
    static let postListData_hot_1Json = Rswift.FileResource(bundle: R.hostingBundle, name: "PostListData_hot_1", pathExtension: "json")
    /// Resource file `PostListData_recommend_1.json`.
    static let postListData_recommend_1Json = Rswift.FileResource(bundle: R.hostingBundle, name: "PostListData_recommend_1", pathExtension: "json")
    /// Resource file `bca7fdafgw1ekhkps65b1j2050050dg4.jpg`.
    static let bca7fdafgw1ekhkps65b1j2050050dg4Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "bca7fdafgw1ekhkps65b1j2050050dg4", pathExtension: "jpg")
    /// Resource file `bca7fdafly1gax1gqd9vmj20c80ayaam.jpg`.
    static let bca7fdafly1gax1gqd9vmj20c80ayaamJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "bca7fdafly1gax1gqd9vmj20c80ayaam", pathExtension: "jpg")
    /// Resource file `bca7fdafly1gax1gqdg6qj20c80avdgl.jpg`.
    static let bca7fdafly1gax1gqdg6qj20c80avdglJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "bca7fdafly1gax1gqdg6qj20c80avdgl", pathExtension: "jpg")
    /// Resource file `bca7fdafly1gax1gqdhouj20c80axaam.jpg`.
    static let bca7fdafly1gax1gqdhouj20c80axaamJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "bca7fdafly1gax1gqdhouj20c80axaam", pathExtension: "jpg")
    /// Resource file `bca7fdafly1gax1gqdnboj20c80atmxp.jpg`.
    static let bca7fdafly1gax1gqdnboj20c80atmxpJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "bca7fdafly1gax1gqdnboj20c80atmxp", pathExtension: "jpg")
    /// Resource file `bca7fdafly1gax1gqehdaj20c80atq3x.jpg`.
    static let bca7fdafly1gax1gqehdaj20c80atq3xJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "bca7fdafly1gax1gqehdaj20c80atq3x", pathExtension: "jpg")
    /// Resource file `bca7fdafly1gax1gqfgsjj20c80axaay.jpg`.
    static let bca7fdafly1gax1gqfgsjj20c80axaayJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "bca7fdafly1gax1gqfgsjj20c80axaay", pathExtension: "jpg")
    /// Resource file `c5aa834fgy1gauzr6venkj20u01hc12f.jpg`.
    static let c5aa834fgy1gauzr6venkj20u01hc12fJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "c5aa834fgy1gauzr6venkj20u01hc12f", pathExtension: "jpg")
    /// Resource file `c5aa834fgy1gauzr86bp5j20pb0w47in.jpg`.
    static let c5aa834fgy1gauzr86bp5j20pb0w47inJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "c5aa834fgy1gauzr86bp5j20pb0w47in", pathExtension: "jpg")
    /// Resource file `c5aa834fgy1gauzr8ok78j20tz12fk8w.jpg`.
    static let c5aa834fgy1gauzr8ok78j20tz12fk8wJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "c5aa834fgy1gauzr8ok78j20tz12fk8w", pathExtension: "jpg")
    /// Resource file `c5aa834fgy1gauzr95r6fj20tw0l3dq4.jpg`.
    static let c5aa834fgy1gauzr95r6fj20tw0l3dq4Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "c5aa834fgy1gauzr95r6fj20tw0l3dq4", pathExtension: "jpg")
    /// Resource file `c5aa834fgy1gauzrb7s5ej20tz13qh5x.jpg`.
    static let c5aa834fgy1gauzrb7s5ej20tz13qh5xJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "c5aa834fgy1gauzrb7s5ej20tz13qh5x", pathExtension: "jpg")
    /// Resource file `c5aa834fly8g97m8ix9lcj20re0regnk.jpg`.
    static let c5aa834fly8g97m8ix9lcj20re0regnkJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "c5aa834fly8g97m8ix9lcj20re0regnk", pathExtension: "jpg")
    /// Resource file `d0c21786ly1gavj2btv6tj20c80790tg.jpg`.
    static let d0c21786ly1gavj2btv6tj20c80790tgJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "d0c21786ly1gavj2btv6tj20c80790tg", pathExtension: "jpg")
    /// Resource file `d0c21786ly1gavj2c0kcej20c8096dh7.jpg`.
    static let d0c21786ly1gavj2c0kcej20c8096dh7Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "d0c21786ly1gavj2c0kcej20c8096dh7", pathExtension: "jpg")
    /// Resource file `d0c21786ly1gavj2cdrkyj20c80720tg.jpg`.
    static let d0c21786ly1gavj2cdrkyj20c80720tgJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "d0c21786ly1gavj2cdrkyj20c80720tg", pathExtension: "jpg")
    /// Resource file `d0c21786ly1gavj2cowp9j20c8083ab4.jpg`.
    static let d0c21786ly1gavj2cowp9j20c8083ab4Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "d0c21786ly1gavj2cowp9j20c8083ab4", pathExtension: "jpg")
    /// Resource file `d0c21786ly1gavj2d17d9j20c808zq3r.jpg`.
    static let d0c21786ly1gavj2d17d9j20c808zq3rJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "d0c21786ly1gavj2d17d9j20c808zq3r", pathExtension: "jpg")
    /// Resource file `d0c21786ly8fsax1ftiifj20ro0ro43g.jpg`.
    static let d0c21786ly8fsax1ftiifj20ro0ro43gJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "d0c21786ly8fsax1ftiifj20ro0ro43g", pathExtension: "jpg")
    /// Resource file `eb5c94aegy1gav2509cp5j20zk0k0n2j.jpg`.
    static let eb5c94aegy1gav2509cp5j20zk0k0n2jJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "eb5c94aegy1gav2509cp5j20zk0k0n2j", pathExtension: "jpg")
    /// Resource file `eb5c94aegy1gav25n5ibjj20zk1h8wuu.jpg`.
    static let eb5c94aegy1gav25n5ibjj20zk1h8wuuJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "eb5c94aegy1gav25n5ibjj20zk1h8wuu", pathExtension: "jpg")
    /// Resource file `eb5c94aegy1gav25ox6dvj20u00k1go9.jpg`.
    static let eb5c94aegy1gav25ox6dvj20u00k1go9Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "eb5c94aegy1gav25ox6dvj20u00k1go9", pathExtension: "jpg")
    /// Resource file `eb5c94aegy1gav26fycwlj20zk1h8drh.jpg`.
    static let eb5c94aegy1gav26fycwlj20zk1h8drhJpg = Rswift.FileResource(bundle: R.hostingBundle, name: "eb5c94aegy1gav26fycwlj20zk1h8drh", pathExtension: "jpg")
    /// Resource file `eb5c94aely8fmvumnl9baj20v90v9q49.jpg`.
    static let eb5c94aely8fmvumnl9baj20v90v9q49Jpg = Rswift.FileResource(bundle: R.hostingBundle, name: "eb5c94aely8fmvumnl9baj20v90v9q49", pathExtension: "jpg")

    /// `bundle.url(forResource: "005tnxzUly8gab4i2r73xj30u00u0js8", withExtension: "jpg")`
    static func tnxzUly8gab4i2r73xj30u00u0js8Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.tnxzUly8gab4i2r73xj30u00u0js8Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "006PdkDogy1gap6ngiyn3j30u011idle", withExtension: "jpg")`
    static func pdkDogy1gap6ngiyn3j30u011idleJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.pdkDogy1gap6ngiyn3j30u011idleJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "006PdkDogy1gap6ngj12ej30u011itf7", withExtension: "jpg")`
    static func pdkDogy1gap6ngj12ej30u011itf7Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.pdkDogy1gap6ngj12ej30u011itf7Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "006PdkDoly8ffywe2fq39j304g04gwed", withExtension: "jpg")`
    static func pdkDoly8ffywe2fq39j304g04gwedJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.pdkDoly8ffywe2fq39j304g04gwedJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "006gWxMEly1gavap86qr9j30ht0qo40t", withExtension: "jpg")`
    static func gWxMEly1gavap86qr9j30ht0qo40tJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.gWxMEly1gavap86qr9j30ht0qo40tJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "006gWxMEly1gavap88gttj30hs0a0dgf", withExtension: "jpg")`
    static func gWxMEly1gavap88gttj30hs0a0dgfJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.gWxMEly1gavap88gttj30hs0a0dgfJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "006gWxMEly1gavap8dywoj30hs0bwq48", withExtension: "jpg")`
    static func gWxMEly1gavap8dywoj30hs0bwq48Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.gWxMEly1gavap8dywoj30hs0bwq48Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "006gWxMEly1gavap8vsqaj30hs0bwgm6", withExtension: "jpg")`
    static func gWxMEly1gavap8vsqaj30hs0bwgm6Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.gWxMEly1gavap8vsqaj30hs0bwgm6Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "006gWxMEly8g0bjpl3ynij30kv0kv773", withExtension: "jpg")`
    static func gWxMEly8g0bjpl3ynij30kv0kv773Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.gWxMEly8g0bjpl3ynij30kv0kv773Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "4e7f0c83gy1gam2misv31j21hc0u016k", withExtension: "jpg")`
    static func e7f0c83gy1gam2misv31j21hc0u016kJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.e7f0c83gy1gam2misv31j21hc0u016kJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "4e7f0c83gy1gam2mjhk8zj21hc0v6wnx", withExtension: "jpg")`
    static func e7f0c83gy1gam2mjhk8zj21hc0v6wnxJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.e7f0c83gy1gam2mjhk8zj21hc0v6wnxJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "4e7f0c83gy1gam2ml6nucj22tc240kjl", withExtension: "jpg")`
    static func e7f0c83gy1gam2ml6nucj22tc240kjlJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.e7f0c83gy1gam2ml6nucj22tc240kjlJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "4e7f0c83gy1gam2mn58d3j22tc240qv5", withExtension: "jpg")`
    static func e7f0c83gy1gam2mn58d3j22tc240qv5Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.e7f0c83gy1gam2mn58d3j22tc240qv5Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "4e7f0c83gy1gam2mp0x4pj22tc240u0x", withExtension: "jpg")`
    static func e7f0c83gy1gam2mp0x4pj22tc240u0xJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.e7f0c83gy1gam2mp0x4pj22tc240u0xJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "4e7f0c83gy1gam2mr1b81j22tc2407wi", withExtension: "jpg")`
    static func e7f0c83gy1gam2mr1b81j22tc2407wiJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.e7f0c83gy1gam2mr1b81j22tc2407wiJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "4e7f0c83ly8g1ho507078j20ro0rojtq", withExtension: "jpg")`
    static func e7f0c83ly8g1ho507078j20ro0rojtqJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.e7f0c83ly8g1ho507078j20ro0rojtqJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "630584a6gy1gau54zgaxhj20m80et0vq", withExtension: "jpg")`
    static func a6gy1gau54zgaxhj20m80et0vqJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a6gy1gau54zgaxhj20m80et0vqJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "630584a6gy1gau54zl806j20m80etmzo", withExtension: "jpg")`
    static func a6gy1gau54zl806j20m80etmzoJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a6gy1gau54zl806j20m80etmzoJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "630584a6gy1gau54zm4dtj20m80dftbv", withExtension: "jpg")`
    static func a6gy1gau54zm4dtj20m80dftbvJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a6gy1gau54zm4dtj20m80dftbvJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "630584a6gy1gau54zyj61j20m80etn07", withExtension: "jpg")`
    static func a6gy1gau54zyj61j20m80etn07Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a6gy1gau54zyj61j20m80etn07Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "630584a6ly8fqs5wwkkmrj20ku0kuta7", withExtension: "jpg")`
    static func a6ly8fqs5wwkkmrj20ku0kuta7Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a6ly8fqs5wwkkmrj20ku0kuta7Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "648ed25bjw8est9nqrtnij20500503yr", withExtension: "jpg")`
    static func ed25bjw8est9nqrtnij20500503yrJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ed25bjw8est9nqrtnij20500503yrJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "6a2afec3gy1gaulykcejqj20t5145wns", withExtension: "jpg")`
    static func a2afec3gy1gaulykcejqj20t5145wnsJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a2afec3gy1gaulykcejqj20t5145wnsJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "6a2afec3jw8fb4ld0qf2gj20e80dsdfz", withExtension: "jpg")`
    static func a2afec3jw8fb4ld0qf2gj20e80dsdfzJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a2afec3jw8fb4ld0qf2gj20e80dsdfzJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "6ec3b446gy1gavd4xud8lj20j60qkwj0", withExtension: "jpg")`
    static func ec3b446gy1gavd4xud8lj20j60qkwj0Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ec3b446gy1gavd4xud8lj20j60qkwj0Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "6ec3b446gy1gavd51jc4lj20j60pmwhl", withExtension: "jpg")`
    static func ec3b446gy1gavd51jc4lj20j60pmwhlJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ec3b446gy1gavd51jc4lj20j60pmwhlJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "6ec3b446gy1gavd523embj20j60pytd6", withExtension: "jpg")`
    static func ec3b446gy1gavd523embj20j60pytd6Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ec3b446gy1gavd523embj20j60pytd6Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "6ec3b446jw1e8qgp5bmzyj2050050aa8", withExtension: "jpg")`
    static func ec3b446jw1e8qgp5bmzyj2050050aa8Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ec3b446jw1e8qgp5bmzyj2050050aa8Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "700a34f6gy1gaunswwui7j20j60pl78e", withExtension: "jpg")`
    static func a34f6gy1gaunswwui7j20j60pl78eJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a34f6gy1gaunswwui7j20j60pl78eJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "700a34f6gy1gaunswxtlrj20j60pkgok", withExtension: "jpg")`
    static func a34f6gy1gaunswxtlrj20j60pkgokJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a34f6gy1gaunswxtlrj20j60pkgokJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "700a34f6gy1gaunswy5qnj20j60pkadk", withExtension: "jpg")`
    static func a34f6gy1gaunswy5qnj20j60pkadkJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a34f6gy1gaunswy5qnj20j60pkadkJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "700a34f6gy1gaunsx2jywj20j60pkaeu", withExtension: "jpg")`
    static func a34f6gy1gaunsx2jywj20j60pkaeuJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a34f6gy1gaunsx2jywj20j60pkaeuJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "700a34f6gy1gaunsxgzixj20j60edmz8", withExtension: "jpg")`
    static func a34f6gy1gaunsxgzixj20j60edmz8Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a34f6gy1gaunsxgzixj20j60edmz8Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "700a34f6gy1gaunsxhp4pj20j60pkn1k", withExtension: "jpg")`
    static func a34f6gy1gaunsxhp4pj20j60pkn1kJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a34f6gy1gaunsxhp4pj20j60pkn1kJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "700a34f6ly8g9a29rjt92j20fn0iqdg8", withExtension: "jpg")`
    static func a34f6ly8g9a29rjt92j20fn0iqdg8Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a34f6ly8g9a29rjt92j20fn0iqdg8Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "76297935ly1gatz89dzblj23402c0qv6", withExtension: "jpg")`
    static func ly1gatz89dzblj23402c0qv6Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ly1gatz89dzblj23402c0qv6Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "76297935ly1gatz8g5rvxj22c03401kz", withExtension: "jpg")`
    static func ly1gatz8g5rvxj22c03401kzJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ly1gatz8g5rvxj22c03401kzJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "76297935ly1gatz8k5itij22c02c01ky", withExtension: "jpg")`
    static func ly1gatz8k5itij22c02c01kyJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ly1gatz8k5itij22c02c01kyJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "76297935ly1gatz8obqvkj22c0340npe", withExtension: "jpg")`
    static func ly1gatz8obqvkj22c0340npeJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ly1gatz8obqvkj22c0340npeJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "76297935ly8g4phfkq68hj20u00u0mzt", withExtension: "jpg")`
    static func ly8g4phfkq68hj20u00u0mztJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.ly8g4phfkq68hj20u00u0mztJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "7f9147a5ly1fzxlgxgzpij20e90fltsj", withExtension: "jpg")`
    static func f9147a5ly1fzxlgxgzpij20e90fltsjJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.f9147a5ly1fzxlgxgzpij20e90fltsjJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "7f9147a5ly1fzxlh4ovuej20e90fl4fo", withExtension: "jpg")`
    static func f9147a5ly1fzxlh4ovuej20e90fl4foJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.f9147a5ly1fzxlh4ovuej20e90fl4foJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "7f9147a5ly1fzxlh6hzdnj20e90fl7me", withExtension: "jpg")`
    static func f9147a5ly1fzxlh6hzdnj20e90fl7meJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.f9147a5ly1fzxlh6hzdnj20e90fl7meJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "8697cf1ely8gashxj3b09j20u00u040v", withExtension: "jpg")`
    static func cf1ely8gashxj3b09j20u00u040vJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.cf1ely8gashxj3b09j20u00u040vJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "8a0b5544gy1gauy2ex786j20u0129aed", withExtension: "jpg")`
    static func a0b5544gy1gauy2ex786j20u0129aedJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a0b5544gy1gauy2ex786j20u0129aedJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "8a0b5544gy1gauy2flua6j20u00hitab", withExtension: "jpg")`
    static func a0b5544gy1gauy2flua6j20u00hitabJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a0b5544gy1gauy2flua6j20u00hitabJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "8a0b5544gy1gauy2g35yoj20u00fomzf", withExtension: "jpg")`
    static func a0b5544gy1gauy2g35yoj20u00fomzfJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a0b5544gy1gauy2g35yoj20u00fomzfJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "8a0b5544gy1gauy2gmkg9j20u00gegnp", withExtension: "jpg")`
    static func a0b5544gy1gauy2gmkg9j20u00gegnpJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a0b5544gy1gauy2gmkg9j20u00gegnpJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "8a0b5544gy1gauy2gz000j20u00n6wgj", withExtension: "jpg")`
    static func a0b5544gy1gauy2gz000j20u00n6wgjJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a0b5544gy1gauy2gz000j20u00n6wgjJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "8a0b5544gy1gauy2hcozsj20u01czdiy", withExtension: "jpg")`
    static func a0b5544gy1gauy2hcozsj20u01czdiyJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a0b5544gy1gauy2hcozsj20u01czdiyJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "8a0b5544jw1e8qgp5bmzyj2050050aa8", withExtension: "jpg")`
    static func a0b5544jw1e8qgp5bmzyj2050050aa8Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.a0b5544jw1e8qgp5bmzyj2050050aa8Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "9dc7402fgy1gavd367p0pj20j60nywic", withExtension: "jpg")`
    static func dc7402fgy1gavd367p0pj20j60nywicJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.dc7402fgy1gavd367p0pj20j60nywicJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "9dc7402fgy1gavd37l9nwj20j60ny44q", withExtension: "jpg")`
    static func dc7402fgy1gavd37l9nwj20j60ny44qJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.dc7402fgy1gavd37l9nwj20j60ny44qJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "9dc7402fgy1gavd38kqjtj20j60nyn1d", withExtension: "jpg")`
    static func dc7402fgy1gavd38kqjtj20j60nyn1dJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.dc7402fgy1gavd38kqjtj20j60nyn1dJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "9dc7402fgy1gavd38wwlrj20j60nyq6y", withExtension: "jpg")`
    static func dc7402fgy1gavd38wwlrj20j60nyq6yJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.dc7402fgy1gavd38wwlrj20j60nyq6yJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "9dc7402fgy1gavd39ba15j20j60nywii", withExtension: "jpg")`
    static func dc7402fgy1gavd39ba15j20j60nywiiJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.dc7402fgy1gavd39ba15j20j60nywiiJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "9dc7402fjw1e8qgp5bmzyj2050050aa8", withExtension: "jpg")`
    static func dc7402fjw1e8qgp5bmzyj2050050aa8Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.dc7402fjw1e8qgp5bmzyj2050050aa8Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "PostListData_hot_1", withExtension: "json")`
    static func postListData_hot_1Json(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.postListData_hot_1Json
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "PostListData_recommend_1", withExtension: "json")`
    static func postListData_recommend_1Json(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.postListData_recommend_1Json
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "bca7fdafgw1ekhkps65b1j2050050dg4", withExtension: "jpg")`
    static func bca7fdafgw1ekhkps65b1j2050050dg4Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.bca7fdafgw1ekhkps65b1j2050050dg4Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "bca7fdafly1gax1gqd9vmj20c80ayaam", withExtension: "jpg")`
    static func bca7fdafly1gax1gqd9vmj20c80ayaamJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.bca7fdafly1gax1gqd9vmj20c80ayaamJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "bca7fdafly1gax1gqdg6qj20c80avdgl", withExtension: "jpg")`
    static func bca7fdafly1gax1gqdg6qj20c80avdglJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.bca7fdafly1gax1gqdg6qj20c80avdglJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "bca7fdafly1gax1gqdhouj20c80axaam", withExtension: "jpg")`
    static func bca7fdafly1gax1gqdhouj20c80axaamJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.bca7fdafly1gax1gqdhouj20c80axaamJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "bca7fdafly1gax1gqdnboj20c80atmxp", withExtension: "jpg")`
    static func bca7fdafly1gax1gqdnboj20c80atmxpJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.bca7fdafly1gax1gqdnboj20c80atmxpJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "bca7fdafly1gax1gqehdaj20c80atq3x", withExtension: "jpg")`
    static func bca7fdafly1gax1gqehdaj20c80atq3xJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.bca7fdafly1gax1gqehdaj20c80atq3xJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "bca7fdafly1gax1gqfgsjj20c80axaay", withExtension: "jpg")`
    static func bca7fdafly1gax1gqfgsjj20c80axaayJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.bca7fdafly1gax1gqfgsjj20c80axaayJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "c5aa834fgy1gauzr6venkj20u01hc12f", withExtension: "jpg")`
    static func c5aa834fgy1gauzr6venkj20u01hc12fJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.c5aa834fgy1gauzr6venkj20u01hc12fJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "c5aa834fgy1gauzr86bp5j20pb0w47in", withExtension: "jpg")`
    static func c5aa834fgy1gauzr86bp5j20pb0w47inJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.c5aa834fgy1gauzr86bp5j20pb0w47inJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "c5aa834fgy1gauzr8ok78j20tz12fk8w", withExtension: "jpg")`
    static func c5aa834fgy1gauzr8ok78j20tz12fk8wJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.c5aa834fgy1gauzr8ok78j20tz12fk8wJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "c5aa834fgy1gauzr95r6fj20tw0l3dq4", withExtension: "jpg")`
    static func c5aa834fgy1gauzr95r6fj20tw0l3dq4Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.c5aa834fgy1gauzr95r6fj20tw0l3dq4Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "c5aa834fgy1gauzrb7s5ej20tz13qh5x", withExtension: "jpg")`
    static func c5aa834fgy1gauzrb7s5ej20tz13qh5xJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.c5aa834fgy1gauzrb7s5ej20tz13qh5xJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "c5aa834fly8g97m8ix9lcj20re0regnk", withExtension: "jpg")`
    static func c5aa834fly8g97m8ix9lcj20re0regnkJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.c5aa834fly8g97m8ix9lcj20re0regnkJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "d0c21786ly1gavj2btv6tj20c80790tg", withExtension: "jpg")`
    static func d0c21786ly1gavj2btv6tj20c80790tgJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.d0c21786ly1gavj2btv6tj20c80790tgJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "d0c21786ly1gavj2c0kcej20c8096dh7", withExtension: "jpg")`
    static func d0c21786ly1gavj2c0kcej20c8096dh7Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.d0c21786ly1gavj2c0kcej20c8096dh7Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "d0c21786ly1gavj2cdrkyj20c80720tg", withExtension: "jpg")`
    static func d0c21786ly1gavj2cdrkyj20c80720tgJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.d0c21786ly1gavj2cdrkyj20c80720tgJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "d0c21786ly1gavj2cowp9j20c8083ab4", withExtension: "jpg")`
    static func d0c21786ly1gavj2cowp9j20c8083ab4Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.d0c21786ly1gavj2cowp9j20c8083ab4Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "d0c21786ly1gavj2d17d9j20c808zq3r", withExtension: "jpg")`
    static func d0c21786ly1gavj2d17d9j20c808zq3rJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.d0c21786ly1gavj2d17d9j20c808zq3rJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "d0c21786ly8fsax1ftiifj20ro0ro43g", withExtension: "jpg")`
    static func d0c21786ly8fsax1ftiifj20ro0ro43gJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.d0c21786ly8fsax1ftiifj20ro0ro43gJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "eb5c94aegy1gav2509cp5j20zk0k0n2j", withExtension: "jpg")`
    static func eb5c94aegy1gav2509cp5j20zk0k0n2jJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.eb5c94aegy1gav2509cp5j20zk0k0n2jJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "eb5c94aegy1gav25n5ibjj20zk1h8wuu", withExtension: "jpg")`
    static func eb5c94aegy1gav25n5ibjj20zk1h8wuuJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.eb5c94aegy1gav25n5ibjj20zk1h8wuuJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "eb5c94aegy1gav25ox6dvj20u00k1go9", withExtension: "jpg")`
    static func eb5c94aegy1gav25ox6dvj20u00k1go9Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.eb5c94aegy1gav25ox6dvj20u00k1go9Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "eb5c94aegy1gav26fycwlj20zk1h8drh", withExtension: "jpg")`
    static func eb5c94aegy1gav26fycwlj20zk1h8drhJpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.eb5c94aegy1gav26fycwlj20zk1h8drhJpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    /// `bundle.url(forResource: "eb5c94aely8fmvumnl9baj20v90v9q49", withExtension: "jpg")`
    static func eb5c94aely8fmvumnl9baj20v90v9q49Jpg(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.eb5c94aely8fmvumnl9baj20v90v9q49Jpg
      return fileResource.bundle.url(forResource: fileResource)
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 81 images.
  struct image {
    /// Image `005tnxzUly8gab4i2r73xj30u00u0js8.jpg`.
    static let tnxzUly8gab4i2r73xj30u00u0js8Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "005tnxzUly8gab4i2r73xj30u00u0js8.jpg")
    /// Image `006PdkDogy1gap6ngiyn3j30u011idle.jpg`.
    static let pdkDogy1gap6ngiyn3j30u011idleJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "006PdkDogy1gap6ngiyn3j30u011idle.jpg")
    /// Image `006PdkDogy1gap6ngj12ej30u011itf7.jpg`.
    static let pdkDogy1gap6ngj12ej30u011itf7Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "006PdkDogy1gap6ngj12ej30u011itf7.jpg")
    /// Image `006PdkDoly8ffywe2fq39j304g04gwed.jpg`.
    static let pdkDoly8ffywe2fq39j304g04gwedJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "006PdkDoly8ffywe2fq39j304g04gwed.jpg")
    /// Image `006gWxMEly1gavap86qr9j30ht0qo40t.jpg`.
    static let gWxMEly1gavap86qr9j30ht0qo40tJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "006gWxMEly1gavap86qr9j30ht0qo40t.jpg")
    /// Image `006gWxMEly1gavap88gttj30hs0a0dgf.jpg`.
    static let gWxMEly1gavap88gttj30hs0a0dgfJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "006gWxMEly1gavap88gttj30hs0a0dgf.jpg")
    /// Image `006gWxMEly1gavap8dywoj30hs0bwq48.jpg`.
    static let gWxMEly1gavap8dywoj30hs0bwq48Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "006gWxMEly1gavap8dywoj30hs0bwq48.jpg")
    /// Image `006gWxMEly1gavap8vsqaj30hs0bwgm6.jpg`.
    static let gWxMEly1gavap8vsqaj30hs0bwgm6Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "006gWxMEly1gavap8vsqaj30hs0bwgm6.jpg")
    /// Image `006gWxMEly8g0bjpl3ynij30kv0kv773.jpg`.
    static let gWxMEly8g0bjpl3ynij30kv0kv773Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "006gWxMEly8g0bjpl3ynij30kv0kv773.jpg")
    /// Image `4e7f0c83gy1gam2misv31j21hc0u016k.jpg`.
    static let e7f0c83gy1gam2misv31j21hc0u016kJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "4e7f0c83gy1gam2misv31j21hc0u016k.jpg")
    /// Image `4e7f0c83gy1gam2mjhk8zj21hc0v6wnx.jpg`.
    static let e7f0c83gy1gam2mjhk8zj21hc0v6wnxJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "4e7f0c83gy1gam2mjhk8zj21hc0v6wnx.jpg")
    /// Image `4e7f0c83gy1gam2ml6nucj22tc240kjl.jpg`.
    static let e7f0c83gy1gam2ml6nucj22tc240kjlJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "4e7f0c83gy1gam2ml6nucj22tc240kjl.jpg")
    /// Image `4e7f0c83gy1gam2mn58d3j22tc240qv5.jpg`.
    static let e7f0c83gy1gam2mn58d3j22tc240qv5Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "4e7f0c83gy1gam2mn58d3j22tc240qv5.jpg")
    /// Image `4e7f0c83gy1gam2mp0x4pj22tc240u0x.jpg`.
    static let e7f0c83gy1gam2mp0x4pj22tc240u0xJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "4e7f0c83gy1gam2mp0x4pj22tc240u0x.jpg")
    /// Image `4e7f0c83gy1gam2mr1b81j22tc2407wi.jpg`.
    static let e7f0c83gy1gam2mr1b81j22tc2407wiJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "4e7f0c83gy1gam2mr1b81j22tc2407wi.jpg")
    /// Image `4e7f0c83ly8g1ho507078j20ro0rojtq.jpg`.
    static let e7f0c83ly8g1ho507078j20ro0rojtqJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "4e7f0c83ly8g1ho507078j20ro0rojtq.jpg")
    /// Image `630584a6gy1gau54zgaxhj20m80et0vq.jpg`.
    static let a6gy1gau54zgaxhj20m80et0vqJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "630584a6gy1gau54zgaxhj20m80et0vq.jpg")
    /// Image `630584a6gy1gau54zl806j20m80etmzo.jpg`.
    static let a6gy1gau54zl806j20m80etmzoJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "630584a6gy1gau54zl806j20m80etmzo.jpg")
    /// Image `630584a6gy1gau54zm4dtj20m80dftbv.jpg`.
    static let a6gy1gau54zm4dtj20m80dftbvJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "630584a6gy1gau54zm4dtj20m80dftbv.jpg")
    /// Image `630584a6gy1gau54zyj61j20m80etn07.jpg`.
    static let a6gy1gau54zyj61j20m80etn07Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "630584a6gy1gau54zyj61j20m80etn07.jpg")
    /// Image `630584a6ly8fqs5wwkkmrj20ku0kuta7.jpg`.
    static let a6ly8fqs5wwkkmrj20ku0kuta7Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "630584a6ly8fqs5wwkkmrj20ku0kuta7.jpg")
    /// Image `648ed25bjw8est9nqrtnij20500503yr.jpg`.
    static let ed25bjw8est9nqrtnij20500503yrJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "648ed25bjw8est9nqrtnij20500503yr.jpg")
    /// Image `6a2afec3gy1gaulykcejqj20t5145wns.jpg`.
    static let a2afec3gy1gaulykcejqj20t5145wnsJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "6a2afec3gy1gaulykcejqj20t5145wns.jpg")
    /// Image `6a2afec3jw8fb4ld0qf2gj20e80dsdfz.jpg`.
    static let a2afec3jw8fb4ld0qf2gj20e80dsdfzJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "6a2afec3jw8fb4ld0qf2gj20e80dsdfz.jpg")
    /// Image `6ec3b446gy1gavd4xud8lj20j60qkwj0.jpg`.
    static let ec3b446gy1gavd4xud8lj20j60qkwj0Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "6ec3b446gy1gavd4xud8lj20j60qkwj0.jpg")
    /// Image `6ec3b446gy1gavd51jc4lj20j60pmwhl.jpg`.
    static let ec3b446gy1gavd51jc4lj20j60pmwhlJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "6ec3b446gy1gavd51jc4lj20j60pmwhl.jpg")
    /// Image `6ec3b446gy1gavd523embj20j60pytd6.jpg`.
    static let ec3b446gy1gavd523embj20j60pytd6Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "6ec3b446gy1gavd523embj20j60pytd6.jpg")
    /// Image `6ec3b446jw1e8qgp5bmzyj2050050aa8.jpg`.
    static let ec3b446jw1e8qgp5bmzyj2050050aa8Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "6ec3b446jw1e8qgp5bmzyj2050050aa8.jpg")
    /// Image `700a34f6gy1gaunswwui7j20j60pl78e.jpg`.
    static let a34f6gy1gaunswwui7j20j60pl78eJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "700a34f6gy1gaunswwui7j20j60pl78e.jpg")
    /// Image `700a34f6gy1gaunswxtlrj20j60pkgok.jpg`.
    static let a34f6gy1gaunswxtlrj20j60pkgokJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "700a34f6gy1gaunswxtlrj20j60pkgok.jpg")
    /// Image `700a34f6gy1gaunswy5qnj20j60pkadk.jpg`.
    static let a34f6gy1gaunswy5qnj20j60pkadkJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "700a34f6gy1gaunswy5qnj20j60pkadk.jpg")
    /// Image `700a34f6gy1gaunsx2jywj20j60pkaeu.jpg`.
    static let a34f6gy1gaunsx2jywj20j60pkaeuJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "700a34f6gy1gaunsx2jywj20j60pkaeu.jpg")
    /// Image `700a34f6gy1gaunsxgzixj20j60edmz8.jpg`.
    static let a34f6gy1gaunsxgzixj20j60edmz8Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "700a34f6gy1gaunsxgzixj20j60edmz8.jpg")
    /// Image `700a34f6gy1gaunsxhp4pj20j60pkn1k.jpg`.
    static let a34f6gy1gaunsxhp4pj20j60pkn1kJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "700a34f6gy1gaunsxhp4pj20j60pkn1k.jpg")
    /// Image `700a34f6ly8g9a29rjt92j20fn0iqdg8.jpg`.
    static let a34f6ly8g9a29rjt92j20fn0iqdg8Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "700a34f6ly8g9a29rjt92j20fn0iqdg8.jpg")
    /// Image `76297935ly1gatz89dzblj23402c0qv6.jpg`.
    static let ly1gatz89dzblj23402c0qv6Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "76297935ly1gatz89dzblj23402c0qv6.jpg")
    /// Image `76297935ly1gatz8g5rvxj22c03401kz.jpg`.
    static let ly1gatz8g5rvxj22c03401kzJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "76297935ly1gatz8g5rvxj22c03401kz.jpg")
    /// Image `76297935ly1gatz8k5itij22c02c01ky.jpg`.
    static let ly1gatz8k5itij22c02c01kyJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "76297935ly1gatz8k5itij22c02c01ky.jpg")
    /// Image `76297935ly1gatz8obqvkj22c0340npe.jpg`.
    static let ly1gatz8obqvkj22c0340npeJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "76297935ly1gatz8obqvkj22c0340npe.jpg")
    /// Image `76297935ly8g4phfkq68hj20u00u0mzt.jpg`.
    static let ly8g4phfkq68hj20u00u0mztJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "76297935ly8g4phfkq68hj20u00u0mzt.jpg")
    /// Image `7f9147a5ly1fzxlgxgzpij20e90fltsj.jpg`.
    static let f9147a5ly1fzxlgxgzpij20e90fltsjJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "7f9147a5ly1fzxlgxgzpij20e90fltsj.jpg")
    /// Image `7f9147a5ly1fzxlh4ovuej20e90fl4fo.jpg`.
    static let f9147a5ly1fzxlh4ovuej20e90fl4foJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "7f9147a5ly1fzxlh4ovuej20e90fl4fo.jpg")
    /// Image `7f9147a5ly1fzxlh6hzdnj20e90fl7me.jpg`.
    static let f9147a5ly1fzxlh6hzdnj20e90fl7meJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "7f9147a5ly1fzxlh6hzdnj20e90fl7me.jpg")
    /// Image `8697cf1ely8gashxj3b09j20u00u040v.jpg`.
    static let cf1ely8gashxj3b09j20u00u040vJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "8697cf1ely8gashxj3b09j20u00u040v.jpg")
    /// Image `8a0b5544gy1gauy2ex786j20u0129aed.jpg`.
    static let a0b5544gy1gauy2ex786j20u0129aedJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "8a0b5544gy1gauy2ex786j20u0129aed.jpg")
    /// Image `8a0b5544gy1gauy2flua6j20u00hitab.jpg`.
    static let a0b5544gy1gauy2flua6j20u00hitabJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "8a0b5544gy1gauy2flua6j20u00hitab.jpg")
    /// Image `8a0b5544gy1gauy2g35yoj20u00fomzf.jpg`.
    static let a0b5544gy1gauy2g35yoj20u00fomzfJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "8a0b5544gy1gauy2g35yoj20u00fomzf.jpg")
    /// Image `8a0b5544gy1gauy2gmkg9j20u00gegnp.jpg`.
    static let a0b5544gy1gauy2gmkg9j20u00gegnpJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "8a0b5544gy1gauy2gmkg9j20u00gegnp.jpg")
    /// Image `8a0b5544gy1gauy2gz000j20u00n6wgj.jpg`.
    static let a0b5544gy1gauy2gz000j20u00n6wgjJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "8a0b5544gy1gauy2gz000j20u00n6wgj.jpg")
    /// Image `8a0b5544gy1gauy2hcozsj20u01czdiy.jpg`.
    static let a0b5544gy1gauy2hcozsj20u01czdiyJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "8a0b5544gy1gauy2hcozsj20u01czdiy.jpg")
    /// Image `8a0b5544jw1e8qgp5bmzyj2050050aa8.jpg`.
    static let a0b5544jw1e8qgp5bmzyj2050050aa8Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "8a0b5544jw1e8qgp5bmzyj2050050aa8.jpg")
    /// Image `9dc7402fgy1gavd367p0pj20j60nywic.jpg`.
    static let dc7402fgy1gavd367p0pj20j60nywicJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "9dc7402fgy1gavd367p0pj20j60nywic.jpg")
    /// Image `9dc7402fgy1gavd37l9nwj20j60ny44q.jpg`.
    static let dc7402fgy1gavd37l9nwj20j60ny44qJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "9dc7402fgy1gavd37l9nwj20j60ny44q.jpg")
    /// Image `9dc7402fgy1gavd38kqjtj20j60nyn1d.jpg`.
    static let dc7402fgy1gavd38kqjtj20j60nyn1dJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "9dc7402fgy1gavd38kqjtj20j60nyn1d.jpg")
    /// Image `9dc7402fgy1gavd38wwlrj20j60nyq6y.jpg`.
    static let dc7402fgy1gavd38wwlrj20j60nyq6yJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "9dc7402fgy1gavd38wwlrj20j60nyq6y.jpg")
    /// Image `9dc7402fgy1gavd39ba15j20j60nywii.jpg`.
    static let dc7402fgy1gavd39ba15j20j60nywiiJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "9dc7402fgy1gavd39ba15j20j60nywii.jpg")
    /// Image `9dc7402fjw1e8qgp5bmzyj2050050aa8.jpg`.
    static let dc7402fjw1e8qgp5bmzyj2050050aa8Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "9dc7402fjw1e8qgp5bmzyj2050050aa8.jpg")
    /// Image `bca7fdafgw1ekhkps65b1j2050050dg4.jpg`.
    static let bca7fdafgw1ekhkps65b1j2050050dg4Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "bca7fdafgw1ekhkps65b1j2050050dg4.jpg")
    /// Image `bca7fdafly1gax1gqd9vmj20c80ayaam.jpg`.
    static let bca7fdafly1gax1gqd9vmj20c80ayaamJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "bca7fdafly1gax1gqd9vmj20c80ayaam.jpg")
    /// Image `bca7fdafly1gax1gqdg6qj20c80avdgl.jpg`.
    static let bca7fdafly1gax1gqdg6qj20c80avdglJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "bca7fdafly1gax1gqdg6qj20c80avdgl.jpg")
    /// Image `bca7fdafly1gax1gqdhouj20c80axaam.jpg`.
    static let bca7fdafly1gax1gqdhouj20c80axaamJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "bca7fdafly1gax1gqdhouj20c80axaam.jpg")
    /// Image `bca7fdafly1gax1gqdnboj20c80atmxp.jpg`.
    static let bca7fdafly1gax1gqdnboj20c80atmxpJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "bca7fdafly1gax1gqdnboj20c80atmxp.jpg")
    /// Image `bca7fdafly1gax1gqehdaj20c80atq3x.jpg`.
    static let bca7fdafly1gax1gqehdaj20c80atq3xJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "bca7fdafly1gax1gqehdaj20c80atq3x.jpg")
    /// Image `bca7fdafly1gax1gqfgsjj20c80axaay.jpg`.
    static let bca7fdafly1gax1gqfgsjj20c80axaayJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "bca7fdafly1gax1gqfgsjj20c80axaay.jpg")
    /// Image `c5aa834fgy1gauzr6venkj20u01hc12f.jpg`.
    static let c5aa834fgy1gauzr6venkj20u01hc12fJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "c5aa834fgy1gauzr6venkj20u01hc12f.jpg")
    /// Image `c5aa834fgy1gauzr86bp5j20pb0w47in.jpg`.
    static let c5aa834fgy1gauzr86bp5j20pb0w47inJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "c5aa834fgy1gauzr86bp5j20pb0w47in.jpg")
    /// Image `c5aa834fgy1gauzr8ok78j20tz12fk8w.jpg`.
    static let c5aa834fgy1gauzr8ok78j20tz12fk8wJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "c5aa834fgy1gauzr8ok78j20tz12fk8w.jpg")
    /// Image `c5aa834fgy1gauzr95r6fj20tw0l3dq4.jpg`.
    static let c5aa834fgy1gauzr95r6fj20tw0l3dq4Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "c5aa834fgy1gauzr95r6fj20tw0l3dq4.jpg")
    /// Image `c5aa834fgy1gauzrb7s5ej20tz13qh5x.jpg`.
    static let c5aa834fgy1gauzrb7s5ej20tz13qh5xJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "c5aa834fgy1gauzrb7s5ej20tz13qh5x.jpg")
    /// Image `c5aa834fly8g97m8ix9lcj20re0regnk.jpg`.
    static let c5aa834fly8g97m8ix9lcj20re0regnkJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "c5aa834fly8g97m8ix9lcj20re0regnk.jpg")
    /// Image `d0c21786ly1gavj2btv6tj20c80790tg.jpg`.
    static let d0c21786ly1gavj2btv6tj20c80790tgJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "d0c21786ly1gavj2btv6tj20c80790tg.jpg")
    /// Image `d0c21786ly1gavj2c0kcej20c8096dh7.jpg`.
    static let d0c21786ly1gavj2c0kcej20c8096dh7Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "d0c21786ly1gavj2c0kcej20c8096dh7.jpg")
    /// Image `d0c21786ly1gavj2cdrkyj20c80720tg.jpg`.
    static let d0c21786ly1gavj2cdrkyj20c80720tgJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "d0c21786ly1gavj2cdrkyj20c80720tg.jpg")
    /// Image `d0c21786ly1gavj2cowp9j20c8083ab4.jpg`.
    static let d0c21786ly1gavj2cowp9j20c8083ab4Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "d0c21786ly1gavj2cowp9j20c8083ab4.jpg")
    /// Image `d0c21786ly1gavj2d17d9j20c808zq3r.jpg`.
    static let d0c21786ly1gavj2d17d9j20c808zq3rJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "d0c21786ly1gavj2d17d9j20c808zq3r.jpg")
    /// Image `d0c21786ly8fsax1ftiifj20ro0ro43g.jpg`.
    static let d0c21786ly8fsax1ftiifj20ro0ro43gJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "d0c21786ly8fsax1ftiifj20ro0ro43g.jpg")
    /// Image `eb5c94aegy1gav2509cp5j20zk0k0n2j.jpg`.
    static let eb5c94aegy1gav2509cp5j20zk0k0n2jJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "eb5c94aegy1gav2509cp5j20zk0k0n2j.jpg")
    /// Image `eb5c94aegy1gav25n5ibjj20zk1h8wuu.jpg`.
    static let eb5c94aegy1gav25n5ibjj20zk1h8wuuJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "eb5c94aegy1gav25n5ibjj20zk1h8wuu.jpg")
    /// Image `eb5c94aegy1gav25ox6dvj20u00k1go9.jpg`.
    static let eb5c94aegy1gav25ox6dvj20u00k1go9Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "eb5c94aegy1gav25ox6dvj20u00k1go9.jpg")
    /// Image `eb5c94aegy1gav26fycwlj20zk1h8drh.jpg`.
    static let eb5c94aegy1gav26fycwlj20zk1h8drhJpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "eb5c94aegy1gav26fycwlj20zk1h8drh.jpg")
    /// Image `eb5c94aely8fmvumnl9baj20v90v9q49.jpg`.
    static let eb5c94aely8fmvumnl9baj20v90v9q49Jpg = Rswift.ImageResource(bundle: R.hostingBundle, name: "eb5c94aely8fmvumnl9baj20v90v9q49.jpg")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "005tnxzUly8gab4i2r73xj30u00u0js8.jpg", bundle: ..., traitCollection: ...)`
    static func tnxzUly8gab4i2r73xj30u00u0js8Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.tnxzUly8gab4i2r73xj30u00u0js8Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "006PdkDogy1gap6ngiyn3j30u011idle.jpg", bundle: ..., traitCollection: ...)`
    static func pdkDogy1gap6ngiyn3j30u011idleJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.pdkDogy1gap6ngiyn3j30u011idleJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "006PdkDogy1gap6ngj12ej30u011itf7.jpg", bundle: ..., traitCollection: ...)`
    static func pdkDogy1gap6ngj12ej30u011itf7Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.pdkDogy1gap6ngj12ej30u011itf7Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "006PdkDoly8ffywe2fq39j304g04gwed.jpg", bundle: ..., traitCollection: ...)`
    static func pdkDoly8ffywe2fq39j304g04gwedJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.pdkDoly8ffywe2fq39j304g04gwedJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "006gWxMEly1gavap86qr9j30ht0qo40t.jpg", bundle: ..., traitCollection: ...)`
    static func gWxMEly1gavap86qr9j30ht0qo40tJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gWxMEly1gavap86qr9j30ht0qo40tJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "006gWxMEly1gavap88gttj30hs0a0dgf.jpg", bundle: ..., traitCollection: ...)`
    static func gWxMEly1gavap88gttj30hs0a0dgfJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gWxMEly1gavap88gttj30hs0a0dgfJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "006gWxMEly1gavap8dywoj30hs0bwq48.jpg", bundle: ..., traitCollection: ...)`
    static func gWxMEly1gavap8dywoj30hs0bwq48Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gWxMEly1gavap8dywoj30hs0bwq48Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "006gWxMEly1gavap8vsqaj30hs0bwgm6.jpg", bundle: ..., traitCollection: ...)`
    static func gWxMEly1gavap8vsqaj30hs0bwgm6Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gWxMEly1gavap8vsqaj30hs0bwgm6Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "006gWxMEly8g0bjpl3ynij30kv0kv773.jpg", bundle: ..., traitCollection: ...)`
    static func gWxMEly8g0bjpl3ynij30kv0kv773Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.gWxMEly8g0bjpl3ynij30kv0kv773Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "4e7f0c83gy1gam2misv31j21hc0u016k.jpg", bundle: ..., traitCollection: ...)`
    static func e7f0c83gy1gam2misv31j21hc0u016kJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.e7f0c83gy1gam2misv31j21hc0u016kJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "4e7f0c83gy1gam2mjhk8zj21hc0v6wnx.jpg", bundle: ..., traitCollection: ...)`
    static func e7f0c83gy1gam2mjhk8zj21hc0v6wnxJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.e7f0c83gy1gam2mjhk8zj21hc0v6wnxJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "4e7f0c83gy1gam2ml6nucj22tc240kjl.jpg", bundle: ..., traitCollection: ...)`
    static func e7f0c83gy1gam2ml6nucj22tc240kjlJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.e7f0c83gy1gam2ml6nucj22tc240kjlJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "4e7f0c83gy1gam2mn58d3j22tc240qv5.jpg", bundle: ..., traitCollection: ...)`
    static func e7f0c83gy1gam2mn58d3j22tc240qv5Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.e7f0c83gy1gam2mn58d3j22tc240qv5Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "4e7f0c83gy1gam2mp0x4pj22tc240u0x.jpg", bundle: ..., traitCollection: ...)`
    static func e7f0c83gy1gam2mp0x4pj22tc240u0xJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.e7f0c83gy1gam2mp0x4pj22tc240u0xJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "4e7f0c83gy1gam2mr1b81j22tc2407wi.jpg", bundle: ..., traitCollection: ...)`
    static func e7f0c83gy1gam2mr1b81j22tc2407wiJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.e7f0c83gy1gam2mr1b81j22tc2407wiJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "4e7f0c83ly8g1ho507078j20ro0rojtq.jpg", bundle: ..., traitCollection: ...)`
    static func e7f0c83ly8g1ho507078j20ro0rojtqJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.e7f0c83ly8g1ho507078j20ro0rojtqJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "630584a6gy1gau54zgaxhj20m80et0vq.jpg", bundle: ..., traitCollection: ...)`
    static func a6gy1gau54zgaxhj20m80et0vqJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a6gy1gau54zgaxhj20m80et0vqJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "630584a6gy1gau54zl806j20m80etmzo.jpg", bundle: ..., traitCollection: ...)`
    static func a6gy1gau54zl806j20m80etmzoJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a6gy1gau54zl806j20m80etmzoJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "630584a6gy1gau54zm4dtj20m80dftbv.jpg", bundle: ..., traitCollection: ...)`
    static func a6gy1gau54zm4dtj20m80dftbvJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a6gy1gau54zm4dtj20m80dftbvJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "630584a6gy1gau54zyj61j20m80etn07.jpg", bundle: ..., traitCollection: ...)`
    static func a6gy1gau54zyj61j20m80etn07Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a6gy1gau54zyj61j20m80etn07Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "630584a6ly8fqs5wwkkmrj20ku0kuta7.jpg", bundle: ..., traitCollection: ...)`
    static func a6ly8fqs5wwkkmrj20ku0kuta7Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a6ly8fqs5wwkkmrj20ku0kuta7Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "648ed25bjw8est9nqrtnij20500503yr.jpg", bundle: ..., traitCollection: ...)`
    static func ed25bjw8est9nqrtnij20500503yrJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ed25bjw8est9nqrtnij20500503yrJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "6a2afec3gy1gaulykcejqj20t5145wns.jpg", bundle: ..., traitCollection: ...)`
    static func a2afec3gy1gaulykcejqj20t5145wnsJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a2afec3gy1gaulykcejqj20t5145wnsJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "6a2afec3jw8fb4ld0qf2gj20e80dsdfz.jpg", bundle: ..., traitCollection: ...)`
    static func a2afec3jw8fb4ld0qf2gj20e80dsdfzJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a2afec3jw8fb4ld0qf2gj20e80dsdfzJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "6ec3b446gy1gavd4xud8lj20j60qkwj0.jpg", bundle: ..., traitCollection: ...)`
    static func ec3b446gy1gavd4xud8lj20j60qkwj0Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ec3b446gy1gavd4xud8lj20j60qkwj0Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "6ec3b446gy1gavd51jc4lj20j60pmwhl.jpg", bundle: ..., traitCollection: ...)`
    static func ec3b446gy1gavd51jc4lj20j60pmwhlJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ec3b446gy1gavd51jc4lj20j60pmwhlJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "6ec3b446gy1gavd523embj20j60pytd6.jpg", bundle: ..., traitCollection: ...)`
    static func ec3b446gy1gavd523embj20j60pytd6Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ec3b446gy1gavd523embj20j60pytd6Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "6ec3b446jw1e8qgp5bmzyj2050050aa8.jpg", bundle: ..., traitCollection: ...)`
    static func ec3b446jw1e8qgp5bmzyj2050050aa8Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ec3b446jw1e8qgp5bmzyj2050050aa8Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "700a34f6gy1gaunswwui7j20j60pl78e.jpg", bundle: ..., traitCollection: ...)`
    static func a34f6gy1gaunswwui7j20j60pl78eJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a34f6gy1gaunswwui7j20j60pl78eJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "700a34f6gy1gaunswxtlrj20j60pkgok.jpg", bundle: ..., traitCollection: ...)`
    static func a34f6gy1gaunswxtlrj20j60pkgokJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a34f6gy1gaunswxtlrj20j60pkgokJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "700a34f6gy1gaunswy5qnj20j60pkadk.jpg", bundle: ..., traitCollection: ...)`
    static func a34f6gy1gaunswy5qnj20j60pkadkJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a34f6gy1gaunswy5qnj20j60pkadkJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "700a34f6gy1gaunsx2jywj20j60pkaeu.jpg", bundle: ..., traitCollection: ...)`
    static func a34f6gy1gaunsx2jywj20j60pkaeuJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a34f6gy1gaunsx2jywj20j60pkaeuJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "700a34f6gy1gaunsxgzixj20j60edmz8.jpg", bundle: ..., traitCollection: ...)`
    static func a34f6gy1gaunsxgzixj20j60edmz8Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a34f6gy1gaunsxgzixj20j60edmz8Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "700a34f6gy1gaunsxhp4pj20j60pkn1k.jpg", bundle: ..., traitCollection: ...)`
    static func a34f6gy1gaunsxhp4pj20j60pkn1kJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a34f6gy1gaunsxhp4pj20j60pkn1kJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "700a34f6ly8g9a29rjt92j20fn0iqdg8.jpg", bundle: ..., traitCollection: ...)`
    static func a34f6ly8g9a29rjt92j20fn0iqdg8Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a34f6ly8g9a29rjt92j20fn0iqdg8Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "76297935ly1gatz89dzblj23402c0qv6.jpg", bundle: ..., traitCollection: ...)`
    static func ly1gatz89dzblj23402c0qv6Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ly1gatz89dzblj23402c0qv6Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "76297935ly1gatz8g5rvxj22c03401kz.jpg", bundle: ..., traitCollection: ...)`
    static func ly1gatz8g5rvxj22c03401kzJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ly1gatz8g5rvxj22c03401kzJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "76297935ly1gatz8k5itij22c02c01ky.jpg", bundle: ..., traitCollection: ...)`
    static func ly1gatz8k5itij22c02c01kyJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ly1gatz8k5itij22c02c01kyJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "76297935ly1gatz8obqvkj22c0340npe.jpg", bundle: ..., traitCollection: ...)`
    static func ly1gatz8obqvkj22c0340npeJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ly1gatz8obqvkj22c0340npeJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "76297935ly8g4phfkq68hj20u00u0mzt.jpg", bundle: ..., traitCollection: ...)`
    static func ly8g4phfkq68hj20u00u0mztJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ly8g4phfkq68hj20u00u0mztJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "7f9147a5ly1fzxlgxgzpij20e90fltsj.jpg", bundle: ..., traitCollection: ...)`
    static func f9147a5ly1fzxlgxgzpij20e90fltsjJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.f9147a5ly1fzxlgxgzpij20e90fltsjJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "7f9147a5ly1fzxlh4ovuej20e90fl4fo.jpg", bundle: ..., traitCollection: ...)`
    static func f9147a5ly1fzxlh4ovuej20e90fl4foJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.f9147a5ly1fzxlh4ovuej20e90fl4foJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "7f9147a5ly1fzxlh6hzdnj20e90fl7me.jpg", bundle: ..., traitCollection: ...)`
    static func f9147a5ly1fzxlh6hzdnj20e90fl7meJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.f9147a5ly1fzxlh6hzdnj20e90fl7meJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "8697cf1ely8gashxj3b09j20u00u040v.jpg", bundle: ..., traitCollection: ...)`
    static func cf1ely8gashxj3b09j20u00u040vJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.cf1ely8gashxj3b09j20u00u040vJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "8a0b5544gy1gauy2ex786j20u0129aed.jpg", bundle: ..., traitCollection: ...)`
    static func a0b5544gy1gauy2ex786j20u0129aedJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a0b5544gy1gauy2ex786j20u0129aedJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "8a0b5544gy1gauy2flua6j20u00hitab.jpg", bundle: ..., traitCollection: ...)`
    static func a0b5544gy1gauy2flua6j20u00hitabJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a0b5544gy1gauy2flua6j20u00hitabJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "8a0b5544gy1gauy2g35yoj20u00fomzf.jpg", bundle: ..., traitCollection: ...)`
    static func a0b5544gy1gauy2g35yoj20u00fomzfJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a0b5544gy1gauy2g35yoj20u00fomzfJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "8a0b5544gy1gauy2gmkg9j20u00gegnp.jpg", bundle: ..., traitCollection: ...)`
    static func a0b5544gy1gauy2gmkg9j20u00gegnpJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a0b5544gy1gauy2gmkg9j20u00gegnpJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "8a0b5544gy1gauy2gz000j20u00n6wgj.jpg", bundle: ..., traitCollection: ...)`
    static func a0b5544gy1gauy2gz000j20u00n6wgjJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a0b5544gy1gauy2gz000j20u00n6wgjJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "8a0b5544gy1gauy2hcozsj20u01czdiy.jpg", bundle: ..., traitCollection: ...)`
    static func a0b5544gy1gauy2hcozsj20u01czdiyJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a0b5544gy1gauy2hcozsj20u01czdiyJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "8a0b5544jw1e8qgp5bmzyj2050050aa8.jpg", bundle: ..., traitCollection: ...)`
    static func a0b5544jw1e8qgp5bmzyj2050050aa8Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.a0b5544jw1e8qgp5bmzyj2050050aa8Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "9dc7402fgy1gavd367p0pj20j60nywic.jpg", bundle: ..., traitCollection: ...)`
    static func dc7402fgy1gavd367p0pj20j60nywicJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.dc7402fgy1gavd367p0pj20j60nywicJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "9dc7402fgy1gavd37l9nwj20j60ny44q.jpg", bundle: ..., traitCollection: ...)`
    static func dc7402fgy1gavd37l9nwj20j60ny44qJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.dc7402fgy1gavd37l9nwj20j60ny44qJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "9dc7402fgy1gavd38kqjtj20j60nyn1d.jpg", bundle: ..., traitCollection: ...)`
    static func dc7402fgy1gavd38kqjtj20j60nyn1dJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.dc7402fgy1gavd38kqjtj20j60nyn1dJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "9dc7402fgy1gavd38wwlrj20j60nyq6y.jpg", bundle: ..., traitCollection: ...)`
    static func dc7402fgy1gavd38wwlrj20j60nyq6yJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.dc7402fgy1gavd38wwlrj20j60nyq6yJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "9dc7402fgy1gavd39ba15j20j60nywii.jpg", bundle: ..., traitCollection: ...)`
    static func dc7402fgy1gavd39ba15j20j60nywiiJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.dc7402fgy1gavd39ba15j20j60nywiiJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "9dc7402fjw1e8qgp5bmzyj2050050aa8.jpg", bundle: ..., traitCollection: ...)`
    static func dc7402fjw1e8qgp5bmzyj2050050aa8Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.dc7402fjw1e8qgp5bmzyj2050050aa8Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bca7fdafgw1ekhkps65b1j2050050dg4.jpg", bundle: ..., traitCollection: ...)`
    static func bca7fdafgw1ekhkps65b1j2050050dg4Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bca7fdafgw1ekhkps65b1j2050050dg4Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bca7fdafly1gax1gqd9vmj20c80ayaam.jpg", bundle: ..., traitCollection: ...)`
    static func bca7fdafly1gax1gqd9vmj20c80ayaamJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bca7fdafly1gax1gqd9vmj20c80ayaamJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bca7fdafly1gax1gqdg6qj20c80avdgl.jpg", bundle: ..., traitCollection: ...)`
    static func bca7fdafly1gax1gqdg6qj20c80avdglJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bca7fdafly1gax1gqdg6qj20c80avdglJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bca7fdafly1gax1gqdhouj20c80axaam.jpg", bundle: ..., traitCollection: ...)`
    static func bca7fdafly1gax1gqdhouj20c80axaamJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bca7fdafly1gax1gqdhouj20c80axaamJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bca7fdafly1gax1gqdnboj20c80atmxp.jpg", bundle: ..., traitCollection: ...)`
    static func bca7fdafly1gax1gqdnboj20c80atmxpJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bca7fdafly1gax1gqdnboj20c80atmxpJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bca7fdafly1gax1gqehdaj20c80atq3x.jpg", bundle: ..., traitCollection: ...)`
    static func bca7fdafly1gax1gqehdaj20c80atq3xJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bca7fdafly1gax1gqehdaj20c80atq3xJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "bca7fdafly1gax1gqfgsjj20c80axaay.jpg", bundle: ..., traitCollection: ...)`
    static func bca7fdafly1gax1gqfgsjj20c80axaayJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.bca7fdafly1gax1gqfgsjj20c80axaayJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "c5aa834fgy1gauzr6venkj20u01hc12f.jpg", bundle: ..., traitCollection: ...)`
    static func c5aa834fgy1gauzr6venkj20u01hc12fJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.c5aa834fgy1gauzr6venkj20u01hc12fJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "c5aa834fgy1gauzr86bp5j20pb0w47in.jpg", bundle: ..., traitCollection: ...)`
    static func c5aa834fgy1gauzr86bp5j20pb0w47inJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.c5aa834fgy1gauzr86bp5j20pb0w47inJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "c5aa834fgy1gauzr8ok78j20tz12fk8w.jpg", bundle: ..., traitCollection: ...)`
    static func c5aa834fgy1gauzr8ok78j20tz12fk8wJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.c5aa834fgy1gauzr8ok78j20tz12fk8wJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "c5aa834fgy1gauzr95r6fj20tw0l3dq4.jpg", bundle: ..., traitCollection: ...)`
    static func c5aa834fgy1gauzr95r6fj20tw0l3dq4Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.c5aa834fgy1gauzr95r6fj20tw0l3dq4Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "c5aa834fgy1gauzrb7s5ej20tz13qh5x.jpg", bundle: ..., traitCollection: ...)`
    static func c5aa834fgy1gauzrb7s5ej20tz13qh5xJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.c5aa834fgy1gauzrb7s5ej20tz13qh5xJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "c5aa834fly8g97m8ix9lcj20re0regnk.jpg", bundle: ..., traitCollection: ...)`
    static func c5aa834fly8g97m8ix9lcj20re0regnkJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.c5aa834fly8g97m8ix9lcj20re0regnkJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "d0c21786ly1gavj2btv6tj20c80790tg.jpg", bundle: ..., traitCollection: ...)`
    static func d0c21786ly1gavj2btv6tj20c80790tgJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.d0c21786ly1gavj2btv6tj20c80790tgJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "d0c21786ly1gavj2c0kcej20c8096dh7.jpg", bundle: ..., traitCollection: ...)`
    static func d0c21786ly1gavj2c0kcej20c8096dh7Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.d0c21786ly1gavj2c0kcej20c8096dh7Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "d0c21786ly1gavj2cdrkyj20c80720tg.jpg", bundle: ..., traitCollection: ...)`
    static func d0c21786ly1gavj2cdrkyj20c80720tgJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.d0c21786ly1gavj2cdrkyj20c80720tgJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "d0c21786ly1gavj2cowp9j20c8083ab4.jpg", bundle: ..., traitCollection: ...)`
    static func d0c21786ly1gavj2cowp9j20c8083ab4Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.d0c21786ly1gavj2cowp9j20c8083ab4Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "d0c21786ly1gavj2d17d9j20c808zq3r.jpg", bundle: ..., traitCollection: ...)`
    static func d0c21786ly1gavj2d17d9j20c808zq3rJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.d0c21786ly1gavj2d17d9j20c808zq3rJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "d0c21786ly8fsax1ftiifj20ro0ro43g.jpg", bundle: ..., traitCollection: ...)`
    static func d0c21786ly8fsax1ftiifj20ro0ro43gJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.d0c21786ly8fsax1ftiifj20ro0ro43gJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "eb5c94aegy1gav2509cp5j20zk0k0n2j.jpg", bundle: ..., traitCollection: ...)`
    static func eb5c94aegy1gav2509cp5j20zk0k0n2jJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.eb5c94aegy1gav2509cp5j20zk0k0n2jJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "eb5c94aegy1gav25n5ibjj20zk1h8wuu.jpg", bundle: ..., traitCollection: ...)`
    static func eb5c94aegy1gav25n5ibjj20zk1h8wuuJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.eb5c94aegy1gav25n5ibjj20zk1h8wuuJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "eb5c94aegy1gav25ox6dvj20u00k1go9.jpg", bundle: ..., traitCollection: ...)`
    static func eb5c94aegy1gav25ox6dvj20u00k1go9Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.eb5c94aegy1gav25ox6dvj20u00k1go9Jpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "eb5c94aegy1gav26fycwlj20zk1h8drh.jpg", bundle: ..., traitCollection: ...)`
    static func eb5c94aegy1gav26fycwlj20zk1h8drhJpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.eb5c94aegy1gav26fycwlj20zk1h8drhJpg, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "eb5c94aely8fmvumnl9baj20v90v9q49.jpg", bundle: ..., traitCollection: ...)`
    static func eb5c94aely8fmvumnl9baj20v90v9q49Jpg(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.eb5c94aely8fmvumnl9baj20v90v9q49Jpg, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
